version: "3"

tasks:
  default:
    cmds:
      - task --list

  run:
    desc: Runs the script with the provided name (clean, upgrade, install)
    cmds:
      - bash scripts/{{.CLI_ARGS}}.sh

  setup:
    desc: Setups the complete dev environment
    cmds:
      - docker compose -f frontend/docker/docker-compose.dev.yml --env-file frontend/app/.env.development -p kita-website-next up -d
